
const arrayPrue=  [
    {
		"ID": "ATF",
		"Nombre": "French Southern and Antarctic Lands",
		"Imagen": "https://flagcdn.com/w320/tf.png",
		"Continente": "Antarctica",
		"Capital": "Port-aux-Français",
		"Subregion": "Subregion no Identificada",
		"Area": 7747,
		"Poblacion": 400,
		"activities": []
	},
	{
		"ID": "COL",
		"Nombre": "Colombia",
		"Imagen": "https://flagcdn.com/w320/co.png",
		"Continente": "South America",
		"Capital": "Bogotá",
		"Subregion": "South America",
		"Area": 1141748,
		"Poblacion": 50882884,
		"activities": []
	},
	{
		"ID": "VEN",
		"Nombre": "Venezuela",
		"Imagen": "https://flagcdn.com/w320/ve.png",
		"Continente": "South America",
		"Capital": "Caracas",
		"Subregion": "South America",
		"Area": 916445,
		"Poblacion": 28435943,
		"activities": []
	},
	{
		"ID": "TJK",
		"Nombre": "Tajikistan",
		"Imagen": "https://flagcdn.com/w320/tj.png",
		"Continente": "Asia",
		"Capital": "Dushanbe",
		"Subregion": "Central Asia",
		"Area": 143100,
		"Poblacion": 9537642,
		"activities": []
	},
	{
		"ID": "IRQ",
		"Nombre": "Iraq",
		"Imagen": "https://flagcdn.com/w320/iq.png",
		"Continente": "Asia",
		"Capital": "Baghdad",
		"Subregion": "Western Asia",
		"Area": 438317,
		"Poblacion": 40222503,
		"activities": []
	},
	{
		"ID": "CIV",
		"Nombre": "Ivory Coast",
		"Imagen": "https://flagcdn.com/w320/ci.png",
		"Continente": "Africa",
		"Capital": "Yamoussoukro",
		"Subregion": "Western Africa",
		"Area": 322463,
		"Poblacion": 26378275,
		"activities": []
	},
	{
		"ID": "CHE",
		"Nombre": "Switzerland",
		"Imagen": "https://flagcdn.com/w320/ch.png",
		"Continente": "Europe",
		"Capital": "Bern",
		"Subregion": "Western Europe",
		"Area": 41284,
		"Poblacion": 8654622,
		"activities": []
	},
	{
		"ID": "BRA",
		"Nombre": "Brazil",
		"Imagen": "https://flagcdn.com/w320/br.png",
		"Continente": "South America",
		"Capital": "Brasília",
		"Subregion": "South America",
		"Area": 8515767,
		"Poblacion": 212559409,
		"activities": []
	},
	{
		"ID": "MUS",
		"Nombre": "Mauritius",
		"Imagen": "https://flagcdn.com/w320/mu.png",
		"Continente": "Africa",
		"Capital": "Port Louis",
		"Subregion": "Eastern Africa",
		"Area": 2040,
		"Poblacion": 1265740,
		"activities": []
	},
	{
		"ID": "CMR",
		"Nombre": "Cameroon",
		"Imagen": "https://flagcdn.com/w320/cm.png",
		"Continente": "Africa",
		"Capital": "Yaoundé",
		"Subregion": "Middle Africa",
		"Area": 475442,
		"Poblacion": 26545864,
		"activities": []
	},
	{
		"ID": "ZWE",
		"Nombre": "Zimbabwe",
		"Imagen": "https://flagcdn.com/w320/zw.png",
		"Continente": "Africa",
		"Capital": "Harare",
		"Subregion": "Southern Africa",
		"Area": 390757,
		"Poblacion": 14862927,
		"activities": []
	},
	{
		"ID": "EGY",
		"Nombre": "Egypt",
		"Imagen": "https://flagcdn.com/w320/eg.png",
		"Continente": "Africa",
		"Capital": "Cairo",
		"Subregion": "Northern Africa",
		"Area": 1002450,
		"Poblacion": 102334403,
		"activities": []
	},
	{
		"ID": "GRD",
		"Nombre": "Grenada",
		"Imagen": "https://flagcdn.com/w320/gd.png",
		"Continente": "North America",
		"Capital": "St. George's",
		"Subregion": "Caribbean",
		"Area": 344,
		"Poblacion": 112519,
		"activities": []
	},
	{
		"ID": "IOT",
		"Nombre": "British Indian Ocean Territory",
		"Imagen": "https://flagcdn.com/w320/io.png",
		"Continente": "Asia",
		"Capital": "Diego Garcia",
		"Subregion": "Eastern Africa",
		"Area": 60,
		"Poblacion": 3000,
		"activities": []
	},
	{
		"ID": "ALA",
		"Nombre": "Åland Islands",
		"Imagen": "https://flagcdn.com/w320/ax.png",
		"Continente": "Europe",
		"Capital": "Mariehamn",
		"Subregion": "Northern Europe",
		"Area": 1580,
		"Poblacion": 29458,
		"activities": []
	},
	{
		"ID": "ROU",
		"Nombre": "Romania",
		"Imagen": "https://flagcdn.com/w320/ro.png",
		"Continente": "Europe",
		"Capital": "Bucharest",
		"Subregion": "Southeast Europe",
		"Area": 238391,
		"Poblacion": 19286123,
		"activities": []
	},
	{
		"ID": "NIC",
		"Nombre": "Nicaragua",
		"Imagen": "https://flagcdn.com/w320/ni.png",
		"Continente": "North America",
		"Capital": "Managua",
		"Subregion": "Central America",
		"Area": 130373,
		"Poblacion": 6624554,
		"activities": []
	},
	{
		"ID": "AGO",
		"Nombre": "Angola",
		"Imagen": "https://flagcdn.com/w320/ao.png",
		"Continente": "Africa",
		"Capital": "Luanda",
		"Subregion": "Middle Africa",
		"Area": 1246700,
		"Poblacion": 32866268,
		"activities": []
	},
	{
		"ID": "TTO",
		"Nombre": "Trinidad and Tobago",
		"Imagen": "https://flagcdn.com/w320/tt.png",
		"Continente": "North America",
		"Capital": "Port of Spain",
		"Subregion": "Caribbean",
		"Area": 5130,
		"Poblacion": 1399491,
		"activities": []
	},
	{
		"ID": "JEY",
		"Nombre": "Jersey",
		"Imagen": "https://flagcdn.com/w320/je.png",
		"Continente": "Europe",
		"Capital": "Saint Helier",
		"Subregion": "Northern Europe",
		"Area": 116,
		"Poblacion": 100800,
		"activities": []
	},
	{
		"ID": "SYR",
		"Nombre": "Syria",
		"Imagen": "https://flagcdn.com/w320/sy.png",
		"Continente": "Asia",
		"Capital": "Damascus",
		"Subregion": "Western Asia",
		"Area": 185180,
		"Poblacion": 17500657,
		"activities": []
	},
	{
		"ID": "GGY",
		"Nombre": "Guernsey",
		"Imagen": "https://flagcdn.com/w320/gg.png",
		"Continente": "Europe",
		"Capital": "St. Peter Port",
		"Subregion": "Northern Europe",
		"Area": 78,
		"Poblacion": 62999,
		"activities": []
	},
	{
		"ID": "FRA",
		"Nombre": "France",
		"Imagen": "https://flagcdn.com/w320/fr.png",
		"Continente": "Europe",
		"Capital": "Paris",
		"Subregion": "Western Europe",
		"Area": 551695,
		"Poblacion": 67391582,
		"activities": []
	},
	{
		"ID": "ASM",
		"Nombre": "American Samoa",
		"Imagen": "https://flagcdn.com/w320/as.png",
		"Continente": "Oceania",
		"Capital": "Pago Pago",
		"Subregion": "Polynesia",
		"Area": 199,
		"Poblacion": 55197,
		"activities": []
	},
	{
		"ID": "MAF",
		"Nombre": "Saint Martin",
		"Imagen": "https://flagcdn.com/w320/mf.png",
		"Continente": "North America",
		"Capital": "Marigot",
		"Subregion": "Caribbean",
		"Area": 53,
		"Poblacion": 38659,
		"activities": []
	},
	{
		"ID": "PRK",
		"Nombre": "North Korea",
		"Imagen": "https://flagcdn.com/w320/kp.png",
		"Continente": "Asia",
		"Capital": "Pyongyang",
		"Subregion": "Eastern Asia",
		"Area": 120538,
		"Poblacion": 25778815,
		"activities": []
	},
	{
		"ID": "KGZ",
		"Nombre": "Kyrgyzstan",
		"Imagen": "https://flagcdn.com/w320/kg.png",
		"Continente": "Asia",
		"Capital": "Bishkek",
		"Subregion": "Central Asia",
		"Area": 199951,
		"Poblacion": 6591600,
		"activities": []
	},
	{
		"ID": "KHM",
		"Nombre": "Cambodia",
		"Imagen": "https://flagcdn.com/w320/kh.png",
		"Continente": "Asia",
		"Capital": "Phnom Penh",
		"Subregion": "South-Eastern Asia",
		"Area": 181035,
		"Poblacion": 16718971,
		"activities": []
	},
	{
		"ID": "GUF",
		"Nombre": "French Guiana",
		"Imagen": "https://flagcdn.com/w320/gf.png",
		"Continente": "South America",
		"Capital": "Cayenne",
		"Subregion": "South America",
		"Area": 83534,
		"Poblacion": 254541,
		"activities": []
	},
	{
		"ID": "KWT",
		"Nombre": "Kuwait",
		"Imagen": "https://flagcdn.com/w320/kw.png",
		"Continente": "Asia",
		"Capital": "Kuwait City",
		"Subregion": "Western Asia",
		"Area": 17818,
		"Poblacion": 4270563,
		"activities": []
	},
	{
		"ID": "TCA",
		"Nombre": "Turks and Caicos Islands",
		"Imagen": "https://flagcdn.com/w320/tc.png",
		"Continente": "North America",
		"Capital": "Cockburn Town",
		"Subregion": "Caribbean",
		"Area": 948,
		"Poblacion": 38718,
		"activities": []
	},
	{
		"ID": "UGA",
		"Nombre": "Uganda",
		"Imagen": "https://flagcdn.com/w320/ug.png",
		"Continente": "Africa",
		"Capital": "Kampala",
		"Subregion": "Eastern Africa",
		"Area": 241550,
		"Poblacion": 45741000,
		"activities": []
	},
	{
		"ID": "VNM",
		"Nombre": "Vietnam",
		"Imagen": "https://flagcdn.com/w320/vn.png",
		"Continente": "Asia",
		"Capital": "Hanoi",
		"Subregion": "South-Eastern Asia",
		"Area": 331212,
		"Poblacion": 97338583,
		"activities": []
	},
	{
		"ID": "CPV",
		"Nombre": "Cape Verde",
		"Imagen": "https://flagcdn.com/w320/cv.png",
		"Continente": "Africa",
		"Capital": "Praia",
		"Subregion": "Western Africa",
		"Area": 4033,
		"Poblacion": 555988,
		"activities": []
	},
	{
		"ID": "UNK",
		"Nombre": "Kosovo",
		"Imagen": "https://flagcdn.com/w320/xk.png",
		"Continente": "Europe",
		"Capital": "Pristina",
		"Subregion": "Southeast Europe",
		"Area": 10908,
		"Poblacion": 1775378,
		"activities": []
	},
	{
		"ID": "KEN",
		"Nombre": "Kenya",
		"Imagen": "https://flagcdn.com/w320/ke.png",
		"Continente": "Africa",
		"Capital": "Nairobi",
		"Subregion": "Eastern Africa",
		"Area": 580367,
		"Poblacion": 53771300,
		"activities": []
	},
	{
		"ID": "CAN",
		"Nombre": "Canada",
		"Imagen": "https://flagcdn.com/w320/ca.png",
		"Continente": "North America",
		"Capital": "Ottawa",
		"Subregion": "North America",
		"Area": 9984670,
		"Poblacion": 38005238,
		"activities": []
	},
	{
		"ID": "CXR",
		"Nombre": "Christmas Island",
		"Imagen": "https://flagcdn.com/w320/cx.png",
		"Continente": "Asia",
		"Capital": "Flying Fish Cove",
		"Subregion": "Australia and New Zealand",
		"Area": 135,
		"Poblacion": 2072,
		"activities": []
	},
	{
		"ID": "BHS",
		"Nombre": "Bahamas",
		"Imagen": "https://flagcdn.com/w320/bs.png",
		"Continente": "North America",
		"Capital": "Nassau",
		"Subregion": "Caribbean",
		"Area": 13943,
		"Poblacion": 393248,
		"activities": []
	},
	{
		"ID": "GHA",
		"Nombre": "Ghana",
		"Imagen": "https://flagcdn.com/w320/gh.png",
		"Continente": "Africa",
		"Capital": "Accra",
		"Subregion": "Western Africa",
		"Area": 238533,
		"Poblacion": 31072945,
		"activities": []
	},
	{
		"ID": "PSE",
		"Nombre": "Palestine",
		"Imagen": "https://flagcdn.com/w320/ps.png",
		"Continente": "Asia",
		"Capital": "Ramallah",
		"Subregion": "Western Asia",
		"Area": 6220,
		"Poblacion": 4803269,
		"activities": []
	},
	{
		"ID": "DZA",
		"Nombre": "Algeria",
		"Imagen": "https://flagcdn.com/w320/dz.png",
		"Continente": "Africa",
		"Capital": "Algiers",
		"Subregion": "Northern Africa",
		"Area": 2381741,
		"Poblacion": 44700000,
		"activities": []
	},
	{
		"ID": "SLV",
		"Nombre": "El Salvador",
		"Imagen": "https://flagcdn.com/w320/sv.png",
		"Continente": "North America",
		"Capital": "San Salvador",
		"Subregion": "Central America",
		"Area": 21041,
		"Poblacion": 6486201,
		"activities": []
	},
	{
		"ID": "IND",
		"Nombre": "India",
		"Imagen": "https://flagcdn.com/w320/in.png",
		"Continente": "Asia",
		"Capital": "New Delhi",
		"Subregion": "Southern Asia",
		"Area": 3287590,
		"Poblacion": 1380004385,
		"activities": []
	},
	{
		"ID": "ISL",
		"Nombre": "Iceland",
		"Imagen": "https://flagcdn.com/w320/is.png",
		"Continente": "Europe",
		"Capital": "Reykjavik",
		"Subregion": "Northern Europe",
		"Area": 103000,
		"Poblacion": 366425,
		"activities": []
	},
	{
		"ID": "MRT",
		"Nombre": "Mauritania",
		"Imagen": "https://flagcdn.com/w320/mr.png",
		"Continente": "Africa",
		"Capital": "Nouakchott",
		"Subregion": "Western Africa",
		"Area": 1030700,
		"Poblacion": 4649660,
		"activities": []
	},
	{
		"ID": "CHL",
		"Nombre": "Chile",
		"Imagen": "https://flagcdn.com/w320/cl.png",
		"Continente": "South America",
		"Capital": "Santiago",
		"Subregion": "South America",
		"Area": 756102,
		"Poblacion": 19116209,
		"activities": []
	},
	{
		"ID": "MTQ",
		"Nombre": "Martinique",
		"Imagen": "https://flagcdn.com/w320/mq.png",
		"Continente": "North America",
		"Capital": "Fort-de-France",
		"Subregion": "Caribbean",
		"Area": 1128,
		"Poblacion": 378243,
		"activities": []
	},
	{
		"ID": "LUX",
		"Nombre": "Luxembourg",
		"Imagen": "https://flagcdn.com/w320/lu.png",
		"Continente": "Europe",
		"Capital": "Luxembourg",
		"Subregion": "Western Europe",
		"Area": 2586,
		"Poblacion": 632275,
		"activities": []
	},
	{
		"ID": "PHL",
		"Nombre": "Philippines",
		"Imagen": "https://flagcdn.com/w320/ph.png",
		"Continente": "Asia",
		"Capital": "Manila",
		"Subregion": "South-Eastern Asia",
		"Area": 342353,
		"Poblacion": 109581085,
		"activities": []
	}
]

export default arrayPrue;